-- 0004_seed.sql  (AUTO-GENERATED from data/seed.js — do not edit by hand)
-- Regenerate with: npm run seed:sql
-- Idempotent: re-running upserts the same rows.

-- campuses
insert into public.campuses (id, name, short, lat, lng) values ('ub', 'University of Botswana', 'UB', -24.6647, 25.9389)
  on conflict (id) do update set name=excluded.name, short=excluded.short, lat=excluded.lat, lng=excluded.lng;
insert into public.campuses (id, name, short, lat, lng) values ('bac', 'Botswana Accountancy College', 'BAC', -24.652, 25.918)
  on conflict (id) do update set name=excluded.name, short=excluded.short, lat=excluded.lat, lng=excluded.lng;
insert into public.campuses (id, name, short, lat, lng) values ('botho', 'Botho University', 'Botho', -24.679, 25.887)
  on conflict (id) do update set name=excluded.name, short=excluded.short, lat=excluded.lat, lng=excluded.lng;
insert into public.campuses (id, name, short, lat, lng) values ('baisago', 'BA ISAGO University', 'BA ISAGO', -24.656, 25.905)
  on conflict (id) do update set name=excluded.name, short=excluded.short, lat=excluded.lat, lng=excluded.lng;

-- combi_routes
insert into public.combi_routes (id, name, color, fare, serves_campus_ids, pickups) values ('r1', 'Blocks → UB Gate', '#C97B5E', 4.5, array['ub'], '[{"lat":-24.647,"lng":25.93},{"lat":-24.6545,"lng":25.935},{"lat":-24.6605,"lng":25.9425},{"lat":-24.66,"lng":25.9355},{"lat":-24.663,"lng":25.937}]'::jsonb)
  on conflict (id) do update set name=excluded.name, color=excluded.color, fare=excluded.fare, serves_campus_ids=excluded.serves_campus_ids, pickups=excluded.pickups;
insert into public.combi_routes (id, name, color, fare, serves_campus_ids, pickups) values ('r2', 'Tlokweng → Main Mall', '#6E8462', 5, array['ub'], '[{"lat":-24.6655,"lng":25.976},{"lat":-24.66,"lng":25.9355},{"lat":-24.663,"lng":25.937}]'::jsonb)
  on conflict (id) do update set name=excluded.name, color=excluded.color, fare=excluded.fare, serves_campus_ids=excluded.serves_campus_ids, pickups=excluded.pickups;
insert into public.combi_routes (id, name, color, fare, serves_campus_ids, pickups) values ('r3', 'Gaborone West → CBD', '#A85A3D', 4.5, array['bac', 'baisago', 'botho'], '[{"lat":-24.662,"lng":25.895},{"lat":-24.6705,"lng":25.8985},{"lat":-24.654,"lng":25.915}]'::jsonb)
  on conflict (id) do update set name=excluded.name, color=excluded.color, fare=excluded.fare, serves_campus_ids=excluded.serves_campus_ids, pickups=excluded.pickups;
insert into public.combi_routes (id, name, color, fare, serves_campus_ids, pickups) values ('r4', 'Broadhurst → Station', '#4F6147', 4.5, array['bac', 'baisago'], '[{"lat":-24.6305,"lng":25.93},{"lat":-24.647,"lng":25.93},{"lat":-24.654,"lng":25.915}]'::jsonb)
  on conflict (id) do update set name=excluded.name, color=excluded.color, fare=excluded.fare, serves_campus_ids=excluded.serves_campus_ids, pickups=excluded.pickups;
insert into public.combi_routes (id, name, color, fare, serves_campus_ids, pickups) values ('r5', 'Mogoditshane → Station', '#8a6d3b', 6.5, array['botho', 'baisago'], '[{"lat":-24.628,"lng":25.865},{"lat":-24.677,"lng":25.89}]'::jsonb)
  on conflict (id) do update set name=excluded.name, color=excluded.color, fare=excluded.fare, serves_campus_ids=excluded.serves_campus_ids, pickups=excluded.pickups;
insert into public.combi_routes (id, name, color, fare, serves_campus_ids, pickups) values ('r6', 'Phakalane → CBD', '#b08968', 7, array['bac'], '[{"lat":-24.585,"lng":25.965},{"lat":-24.654,"lng":25.915}]'::jsonb)
  on conflict (id) do update set name=excluded.name, color=excluded.color, fare=excluded.fare, serves_campus_ids=excluded.serves_campus_ids, pickups=excluded.pickups;
insert into public.combi_routes (id, name, color, fare, serves_campus_ids, pickups) values ('r7', 'Block 9/10 → UB', '#93A786', 4.5, array['ub'], '[{"lat":-24.67,"lng":25.9305},{"lat":-24.6755,"lng":25.9255},{"lat":-24.663,"lng":25.937}]'::jsonb)
  on conflict (id) do update set name=excluded.name, color=excluded.color, fare=excluded.fare, serves_campus_ids=excluded.serves_campus_ids, pickups=excluded.pickups;

-- listings
insert into public.listings (id, title, neighbourhood, room_type, rent, deposit, verified, beds, baths, amenities, description, lat, lng) values ('blk7-studio', 'Bright studio, Block 7', 'Block 7', 'studio', 2900, 2900, true, 1, 1, '["Furnished","Prepaid electricity","Wi-Fi ready","Security bars","Study desk"]'::jsonb, 'A self-contained studio a short walk from the UB gate — your own bathroom, kitchenette, and a quiet street.', -24.653499999999998, 25.934199999999997)
  on conflict (id) do update set title=excluded.title, neighbourhood=excluded.neighbourhood, room_type=excluded.room_type, rent=excluded.rent, deposit=excluded.deposit, verified=excluded.verified, beds=excluded.beds, baths=excluded.baths, amenities=excluded.amenities, description=excluded.description, lat=excluded.lat, lng=excluded.lng;
insert into public.listings (id, title, neighbourhood, room_type, rent, deposit, verified, beds, baths, amenities, description, lat, lng) values ('blk6-private', 'Private room, family home in Block 6', 'Block 6', 'private', 1800, 1800, true, 1, 1, '["Shared kitchen","Water included","Wi-Fi","Parking","Furnished"]'::jsonb, 'Private room with a shared kitchen in a secure family compound. Great combi access in every direction.', -24.6479, 25.9311)
  on conflict (id) do update set title=excluded.title, neighbourhood=excluded.neighbourhood, room_type=excluded.room_type, rent=excluded.rent, deposit=excluded.deposit, verified=excluded.verified, beds=excluded.beds, baths=excluded.baths, amenities=excluded.amenities, description=excluded.description, lat=excluded.lat, lng=excluded.lng;
insert into public.listings (id, title, neighbourhood, room_type, rent, deposit, verified, beds, baths, amenities, description, lat, lng) values ('ext-shared', 'Shared twin room near UB', 'Extension 12', 'shared', 1300, 1300, true, 2, 1, '["Shared kitchen","Water included","Walk to campus","Study desk"]'::jsonb, 'Split the rent with a roommate, minutes on foot from UB. Best value for first-years.', -24.6594, 25.9361)
  on conflict (id) do update set title=excluded.title, neighbourhood=excluded.neighbourhood, room_type=excluded.room_type, rent=excluded.rent, deposit=excluded.deposit, verified=excluded.verified, beds=excluded.beds, baths=excluded.baths, amenities=excluded.amenities, description=excluded.description, lat=excluded.lat, lng=excluded.lng;
insert into public.listings (id, title, neighbourhood, room_type, rent, deposit, verified, beds, baths, amenities, description, lat, lng) values ('blk8-studio', 'New-build studio, Block 8', 'Block 8', 'studio', 3200, 3200, false, 1, 1, '["En-suite bathroom","Prepaid electricity","Furnished","Security bars"]'::jsonb, 'A brand-new self-contained studio. Inspection pending — request a verified visit before you book.', -24.659699999999997, 25.941499999999998)
  on conflict (id) do update set title=excluded.title, neighbourhood=excluded.neighbourhood, room_type=excluded.room_type, rent=excluded.rent, deposit=excluded.deposit, verified=excluded.verified, beds=excluded.beds, baths=excluded.baths, amenities=excluded.amenities, description=excluded.description, lat=excluded.lat, lng=excluded.lng;
insert into public.listings (id, title, neighbourhood, room_type, rent, deposit, verified, beds, baths, amenities, description, lat, lng) values ('tlokweng-private', 'Private room in Tlokweng', 'Tlokweng', 'private', 1600, 1600, true, 1, 1, '["Shared kitchen","Wi-Fi","Parking","Water included"]'::jsonb, 'Spacious private room on the Tlokweng combi line straight to UB. Quieter, greener, cheaper.', -24.6662, 25.975099999999998)
  on conflict (id) do update set title=excluded.title, neighbourhood=excluded.neighbourhood, room_type=excluded.room_type, rent=excluded.rent, deposit=excluded.deposit, verified=excluded.verified, beds=excluded.beds, baths=excluded.baths, amenities=excluded.amenities, description=excluded.description, lat=excluded.lat, lng=excluded.lng;
insert into public.listings (id, title, neighbourhood, room_type, rent, deposit, verified, beds, baths, amenities, description, lat, lng) values ('phakalane-studio', 'Upmarket studio, Phakalane', 'Phakalane', 'studio', 3500, 3500, true, 1, 1, '["En-suite bathroom","Furnished","Wi-Fi","Parking","Backup water"]'::jsonb, 'A premium studio in leafy Phakalane for students who want their own space and don’t mind the commute.', -24.5839, 25.9657)
  on conflict (id) do update set title=excluded.title, neighbourhood=excluded.neighbourhood, room_type=excluded.room_type, rent=excluded.rent, deposit=excluded.deposit, verified=excluded.verified, beds=excluded.beds, baths=excluded.baths, amenities=excluded.amenities, description=excluded.description, lat=excluded.lat, lng=excluded.lng;
insert into public.listings (id, title, neighbourhood, room_type, rent, deposit, verified, beds, baths, amenities, description, lat, lng) values ('gabwest2-private', 'Private room, Gaborone West Phase 2', 'Gaborone West Phase 2', 'private', 1750, 1750, true, 1, 1, '["Shared kitchen","Wi-Fi","Water included","Furnished"]'::jsonb, 'Close to BAC, BA ISAGO and Botho via the West–CBD combi. Tidy room in a well-kept yard.', -24.6628, 25.896)
  on conflict (id) do update set title=excluded.title, neighbourhood=excluded.neighbourhood, room_type=excluded.room_type, rent=excluded.rent, deposit=excluded.deposit, verified=excluded.verified, beds=excluded.beds, baths=excluded.baths, amenities=excluded.amenities, description=excluded.description, lat=excluded.lat, lng=excluded.lng;
insert into public.listings (id, title, neighbourhood, room_type, rent, deposit, verified, beds, baths, amenities, description, lat, lng) values ('phase4-shared', 'Shared room, Phase 4', 'Phase 4', 'shared', 1200, 1200, true, 2, 1, '["Shared kitchen","Water included","Wi-Fi"]'::jsonb, 'Budget shared room with easy combi links toward the CBD campuses.', -24.669900000000002, 25.8979)
  on conflict (id) do update set title=excluded.title, neighbourhood=excluded.neighbourhood, room_type=excluded.room_type, rent=excluded.rent, deposit=excluded.deposit, verified=excluded.verified, beds=excluded.beds, baths=excluded.baths, amenities=excluded.amenities, description=excluded.description, lat=excluded.lat, lng=excluded.lng;
insert into public.listings (id, title, neighbourhood, room_type, rent, deposit, verified, beds, baths, amenities, description, lat, lng) values ('broadhurst-studio', 'Studio flat, Broadhurst', 'Broadhurst', 'studio', 2700, 2700, true, 1, 1, '["Furnished","Prepaid electricity","Wi-Fi","Security bars"]'::jsonb, 'Independent studio in busy Broadhurst, walkable to shops and on the Station combi route.', -24.631500000000003, 25.9308)
  on conflict (id) do update set title=excluded.title, neighbourhood=excluded.neighbourhood, room_type=excluded.room_type, rent=excluded.rent, deposit=excluded.deposit, verified=excluded.verified, beds=excluded.beds, baths=excluded.baths, amenities=excluded.amenities, description=excluded.description, lat=excluded.lat, lng=excluded.lng;
insert into public.listings (id, title, neighbourhood, room_type, rent, deposit, verified, beds, baths, amenities, description, lat, lng) values ('mogoditshane-private', 'Private room, Mogoditshane', 'Mogoditshane', 'private', 1400, 1400, false, 1, 1, '["Shared kitchen","Water included","Parking"]'::jsonb, 'Affordable private room west of the city. Inspection pending.', -24.6271, 25.8661)
  on conflict (id) do update set title=excluded.title, neighbourhood=excluded.neighbourhood, room_type=excluded.room_type, rent=excluded.rent, deposit=excluded.deposit, verified=excluded.verified, beds=excluded.beds, baths=excluded.baths, amenities=excluded.amenities, description=excluded.description, lat=excluded.lat, lng=excluded.lng;
insert into public.listings (id, title, neighbourhood, room_type, rent, deposit, verified, beds, baths, amenities, description, lat, lng) values ('blk9-private', 'Private en-suite, Block 9', 'Block 9', 'private', 1900, 1900, true, 1, 1, '["En-suite bathroom","Shared kitchen","Wi-Fi","Furnished"]'::jsonb, 'Private room with its own bathroom, on the Block 9/10 combi line to UB.', -24.669300000000003, 25.9298)
  on conflict (id) do update set title=excluded.title, neighbourhood=excluded.neighbourhood, room_type=excluded.room_type, rent=excluded.rent, deposit=excluded.deposit, verified=excluded.verified, beds=excluded.beds, baths=excluded.baths, amenities=excluded.amenities, description=excluded.description, lat=excluded.lat, lng=excluded.lng;
insert into public.listings (id, title, neighbourhood, room_type, rent, deposit, verified, beds, baths, amenities, description, lat, lng) values ('blk10-shared', 'Shared room, Block 10', 'Block 10', 'shared', 1250, 1250, true, 2, 1, '["Shared kitchen","Water included","Study desk"]'::jsonb, 'Cheap and cheerful shared room with a direct combi to UB.', -24.676099999999998, 25.9264)
  on conflict (id) do update set title=excluded.title, neighbourhood=excluded.neighbourhood, room_type=excluded.room_type, rent=excluded.rent, deposit=excluded.deposit, verified=excluded.verified, beds=excluded.beds, baths=excluded.baths, amenities=excluded.amenities, description=excluded.description, lat=excluded.lat, lng=excluded.lng;
insert into public.listings (id, title, neighbourhood, room_type, rent, deposit, verified, beds, baths, amenities, description, lat, lng) values ('naledi-shared', 'Shared room, Old Naledi', 'Old Naledi', 'shared', 1100, 1100, false, 2, 1, '["Shared kitchen","Water included"]'::jsonb, 'The cheapest option on Nimbus right now. Inspection pending — book a verified visit first.', -24.674699999999998, 25.911099999999998)
  on conflict (id) do update set title=excluded.title, neighbourhood=excluded.neighbourhood, room_type=excluded.room_type, rent=excluded.rent, deposit=excluded.deposit, verified=excluded.verified, beds=excluded.beds, baths=excluded.baths, amenities=excluded.amenities, description=excluded.description, lat=excluded.lat, lng=excluded.lng;
insert into public.listings (id, title, neighbourhood, room_type, rent, deposit, verified, beds, baths, amenities, description, lat, lng) values ('blk7-ensuite', 'En-suite studio, Block 7', 'Block 7', 'studio', 3100, 3100, true, 1, 1, '["En-suite bathroom","Furnished","Prepaid electricity","Wi-Fi","Parking"]'::jsonb, 'Premium en-suite studio walkable to UB, with secure parking and fast Wi-Fi.', -24.6556, 25.935699999999997)
  on conflict (id) do update set title=excluded.title, neighbourhood=excluded.neighbourhood, room_type=excluded.room_type, rent=excluded.rent, deposit=excluded.deposit, verified=excluded.verified, beds=excluded.beds, baths=excluded.baths, amenities=excluded.amenities, description=excluded.description, lat=excluded.lat, lng=excluded.lng;
